[package]
name = "rvault-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
rvault-core = { path = "../rvault-core" }
ratatui = "0.30.0"
anyhow = "1.0.100"
crossterm = "0.29.0"
